baseurl = "http://pgruenbacher.github.io/"
languageCode = "en-us"
title = "Modicum"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

theme = "redlounge"

[params]
  description = "Paul Gruenbacher's repositories and blog"
  author = "Paul Gruenbacher"
  #redlounge configurations
  sidebartitle="Modicum"
  sidebartagline="Posts by Paul Gruenbacher"

[[menu.main]]
    name = "Blog"
    url = "/posts"

